name: Build Yield WebApp Preview
on:
  pull_request:
    branches:
      - webapp-yield
  push:
    branches:
      - webapp-yield

jobs:
  master:
    if: "! startsWith(github.event.head_commit.message, '[CI Skip]')"
    name: Deploy Yield WebApp Preview
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_PAT }}
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'yarn'
      env:
        TRANSAK_API_KEY: ${{ secrets.TRANSAK_API_KEY }}
        COINBASE_PAY_ID: ${{ secrets.COINBASE_PAY_ID }}
        NFT_MINTING_HOST: ${{ secrets.NFT_MINTING_HOST }}
    - run: yarn install --immutable | grep -v 'YN0013'
    - run: yarn webapp:build
    - name: Publish to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: ${{ vars.CLOUDFLARE_PAGES_YIELD_PROJECT_NAME }}
        gitHubToken: ${{ secrets.GH_AUTOMATION_TOKEN }}
        branch: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || 'main' }}
        directory: './packages/webapp/build'
        wranglerVersion: '3'
